include:
  - path: ./server/docker-compose.yml

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_URL: http://localhost:8080 # This value will be used during local Docker build
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env # Keep this for other local client-side environment variables if any
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
